name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - feature/integrate-cicd
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      java_changed: ${{ steps.filter.outputs.java }}
      python_changed: ${{ steps.filter.outputs.speech-analyze }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            java:
              - 'java/**'
            python:
              - 'python/**'

  build-python:
    needs: detect-changes
    if: needs.detect-changes.outputs.python_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. Build và push Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Sử dụng Access Token thay cho mật khẩu

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/echo-english:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
